### PR TITLE
graphics: Preserve video memory during sleep

### PR DESCRIPTION
**Pull request by crawfxrd**
The NVIDIA driver has two methods to save video memory during suspend:

- Save allocations in an unnamed temporary file
- S0ix-based power management

These are exclusive. Systems using S3 should only use the first, and
systems using S0ix should only use the second.

Requires: pop-os/nvidia-graphics-drivers#128
Ref: pop-os/nvidia-graphics-drivers@de515f69a481
Link: https://download.nvidia.com/XFree86/Linux-x86_64/470.86/README/powermanagement.html#PreserveAllVide719f0

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
This isn't currently in a staging repo even though it shows as built, may need to test by building locally.

**Comment by 13r0ck** [comment]
This can't be approved until it can be pulled from a staging repo, but after some preliminary testing by building locally with pop-os/nvidia-graphics-drivers#128 this works correctly.

**Review by 13r0ck — APPROVED** [review]
Tested on Gaze16 and Addw2 on all 3 graphics profiles w/ pop-os/nvidia-graphics-dirvers#128 . Sleep still works correctly.

**Comment by crawfxrd** [comment]
This needs to be tested on a TGL-U board as well, as those are the only ones using s2idle.

**Comment by 13r0ck** [comment]
On Kudu6, the system fails to start after a suspend

**Review by 13r0ck — CHANGES_REQUESTED** [review]
On Kudu6, the system fails to start after a suspend

**Comment by crawfxrd** [comment]
Is there a SATA drive still in it? If so, it must be removed.
If not, are there any nvidia or amdgpu errors in journalctl for that boot?

And what is the output of:
```
cat /proc/driver/nvidia/params
```

**Comment by 13r0ck** [comment]
Oh, I wasn't fully up to date on the kudu6/sata issues. Switching to nvme fixed the issue. Let me finish some testing, then this will probably be approved.

**Review by 13r0ck — APPROVED** [review]
Kudu6 has no regressions on 21.10, 21.04, 20.04

There is an issue with the kudu6 on 20.04 when starting from suspend. CLI says
`Can't reactivate KBD Port`, then proceeds to gnome shell. But that is not a regression. It exists without this PR

**Pull request merged**
