### PR TITLE
Update fan curve

### LINKED ISSUE #69: Thelio Major Fan is Loud at Idle
**Distribution**
 
    david@system76-pc:~$ cat /etc/os-release
    NAME="Ubuntu"
    VERSION="18.04.2 LTS (Bionic Beaver)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 18.04.2 LTS"
    VERSION_ID="18.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=bionic
    UBUNTU_CODENAME=bionic
 
**Related Application and/or Package Version**

    david@system76-pc:~$ apt policy system76-power
    system76-power:
      Installed: 1.0.0~1553639437~18.04~ce5c6e4~dev
      Candidate: 1.0.0~1553639437~18.04~ce5c6e4~dev
      Version table:
     *** 1.0.0~1553639437~18.04~ce5c6e4~dev 500
            500 http://ppa.launchpad.net/system76-dev/stable/ubuntu bionic/main amd64 Packages
            100 /var/lib/dpkg/status

**Issue/Bug Description:**

At idle, the fan on my new thelio major is _loud_. It looks like(?) the system reports to the fan that the cpu is running much hotter than it actually is (tctl v. tdie), so the fan is spinning at full tilt:

    david@system76-pc:~$ sensors
    iwlwifi-virtual-0
    Adapter: Virtual device
    temp1:        +37.0°C  
    
    k10temp-pci-00d3
    Adapter: PCI adapter
    Tdie:         +43.8°C  (high = +70.0°C)
    Tctl:         +70.8°C  
    
    k10temp-pci-00c3
    Adapter: PCI adapter
    Tdie:         +43.8°C  (high = +70.0°C)
    Tctl:         +70.8°C  
    
    amdgpu-pci-4100
    Adapter: PCI adapter
    vddgfx:       +0.77 V  
    fan1:        1482 RPM
    temp1:        +28.0°C  (crit = +94.0°C, hyst = -273.1°C)
    power1:        5.19 W  (cap =  35.00 W)
    
    k10temp-pci-00db
    Adapter: PCI adapter
    Tdie:         +32.5°C  (high = +70.0°C)
    Tctl:         +59.5°C  
    
    k10temp-pci-00cb
    Adapter: PCI adapter
    Tdie:         +34.1°C  (high = +70.0°C)
    Tctl:         +61.1°C  

**Expected behavior**

The fan should run slower when the cpu is not that hot.

### PR DESCRIPTION
**Pull request by jackpot51**
The original fan curve almost always spun the fans at idle, and had a very low maximum fan speed temperature of 65 degrees. This curve was taken from the motherboard defaults.

original_fan_curve

This new curve will keep all models of fans we have used off until 40 degrees C, then will spin up the fans more gradually until reaching maximum speed at 75 degrees C.

new_fan_curve

Fixes #69

### CODE REVIEW

**Comment by jackpot51** [comment]
@brs17 maybe a thelio and thelio massive test would be good?

**Comment by mmstick** [comment]
Confirmed working on the Thelio systems with AMD and NVIDIA graphics, or multiple graphics cards. Highest temperature among all CPUs and GPUs determines the fan curve. If both CPU and GPU temperatures are below 40C, fans stop.

**Comment by felicianotech** [comment]
I would love if this fixes the fan for my Thelio. I don't even have a graphics card. The temp is at 16C typically and the fan is always on a loud.

I assume without dedicated graphics, this will still work relying solely on the CPU temp?

**Comment by mmstick** [comment]
Yes, the highest sensor reading determines the fan speed.

**Comment by jpritikin** [comment]
When will this change make it out to a release?

**Comment by felicianotech** [comment]
^ same question from me but also, this will go out to Ubuntu in addition to Pop OS right?

**Comment by mmstick** [comment]
@jpritikin Already has

@felicianotech The system76-power binary is automatically built for all supported versions of Pop!_OS and Ubuntu. There's no reason to withhold updates to anyone.

**Comment by ilya** [comment]
For what it's worth, I find this new curve too aggressive still. The fan in my Thelio is super loud at 40% and the idle temp is pretty close to 40C. I ended up connecting the fan directly to the motherboard and tweaking the curve in the BIOS to rise more gradually after 40C.

Could you post instructions on how to build this binary locally so we can continue using the IO board?

I have to say the CPU fan is a real thorn in the side of an elegant hardware experience. I didn't expect to be mucking around with any of this when I bought the machine.

**Comment by mmstick** [comment]
@ilya If you add the staging repository for `s76powerconf`, you get a configuration file which you can use to alter the fan curve. See https://github.com/pop-os/system76-power/pull/93. Staging repositories can be added by cloning the `pop-os/pop` repository and running the apt script to add it.

```sh
git clone https://github.com/pop-os/pop
./pop/scripts/apt add s76powerconf
```

After upgrading, you'll see a new template at `/usr/lib/system76-power/config.toml`. You can copy the fan curve section to a new file at `/etc/system76-power/config.toml` like so:

```toml
[fans]
curves.standard = [ { temp = 39, duty =   0 },
                    { temp = 40, duty =  40 },
                    { temp = 50, duty =  50 },
                    { temp = 60, duty =  65 },
                    { temp = 70, duty =  85 },
                    { temp = 75, duty = 100 } ]
```

Changes made to `/etc/system76-power/config.toml` override the values defined in `/usr/lib/system76-power/config.toml`.

**Comment by jpritikin** [comment]
Just for fun, I changed the curve to,

```
curves.standard = [ { temp = 49, duty =   0 },
                 { temp = 50, duty =  50 },
                 { temp = 60, duty =  65 },
                 { temp = 70, duty =  85 },
                 { temp = 75, duty = 100 } ]
```

But sensors reports that the fan is still spinning even with no temp measurement above 49C,

```
iwlwifi-virtual-0
Adapter: Virtual device
temp1:        +44.0°C  

system76_io-virtual-0
Adapter: Virtual device
CPUF:        1920 RPM
INTF:           0 RPM

amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:       +0.86 V  
fan1:        1867 RPM  (min =    0 RPM, max = 5300 RPM)
temp1:        +33.0°C  (crit = +94.0°C, hyst = -273.1°C)
power1:       37.06 W  (cap = 145.00 W)

k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +40.4°C  (high = +70.0°C)
Tctl:         +40.4°C  

```

What's up with that? I restarted system76-power with systemctl. Do I need to reboot too?

**Comment by mmstick** [comment]
Restarting the daemon is enough. I don't have a Thelio in front of me to test with at the moment.

**Comment by jpritikin** [comment]
Hm then something isn't working. Let me know when I can test again.

**Comment by jackpot51** [comment]
You may need a firmware update for your thelio-io. Does a fan connected to INTF stop spinning as expected?

**Comment by jpritikin** [comment]
> You may need a firmware update for your thelio-io.

When I run system76-firmware, it says that there was an error looking for updates (running on Ubuntu Disco). Do I need to use PopOS to update the firmware?

**Comment by lindsayad** [comment]
Can you say exactly what temperatures are considered? E.g. `Tctl` vs `Tdie`?

**Pull request merged**
