### PR TITLE
Install files to vendor location

### PR DESCRIPTION
**Pull request by crawfxrd**
- Package systemd service files should be installed to `/usr/lib`
- Package DBus conf files should be installed to `/usr/share`
- `/etc` should be used by sysadmins to create overrides.

Resolves: #255

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
I'm getting an error trying to upgrade to this version:

```
system76@pop-os:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  system76-power
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/749 kB of archives.
After this operation, 1,024 B disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 253036 files and directories currently installed.)
Preparing to unpack .../system76-power_1.1.16~1626132380~21.04~3716ca7_amd64.deb ...
Unpacking system76-power (1.1.16~1626132380~21.04~3716ca7) over (1.1.16~1626117109~21.04~e2c47ac) ...
dpkg: error processing archive /var/cache/apt/archives/system76-power_1.1.16~1626132380~21.04~3716ca7_amd64.deb (--unpack):
 unable to open '/usr/lib/systemd/system/system76-power.service.dpkg-new': No such file or directory
No apport report written because the error message indicates an issue on the local system
                                                                                         Errors were encountered while processing:
 /var/cache/apt/archives/system76-power_1.1.16~1626132380~21.04~3716ca7_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by crawfxrd** [comment]
Disabled `dh_installsystemd` to avoid the dpkg error. Installing/removing the service file is handled by the Makefile targets.

Used a `maintscript` file to move the old files to the new locations.

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
After upgrading from 5a46c86 (the current release) to 4ea0d7e, the files in `/usr/` are present, but the files in `/etc/` are also still present. Is this expected?

**Comment by crawfxrd** [comment]
No, they should be moved. Likely due to specifying `1.1.17~` for the previous version.

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
This failed to build on the build server:
```
cargo build "--release" "--frozen"
error: failed to get `clap` as a dependency of package `system76-power v1.1.18 (/<<PKGBUILDDIR>>)`

Caused by:
  attempting to make an HTTP request, but --frozen was specified
make[2]: *** [Makefile:60: target/release/system76-power] Error 101
```

It succeeded building locally, but I'm still not seeing the `/etc/` files get moved/removed.

**Comment by crawfxrd** [comment]
Yeah, I don't know why it's trying to fetch clap now if it was working earlier.

I _think_ it will work with packages built by the build server; It works locally if I add a `~1` to the version.

**Comment by crawfxrd** [comment]
`override_dh_installsystemd` somehow breaks vendoring?

**Comment by crawfxrd** [comment]
As far as I can tell, `cargo vendor` is either silently failing or just not running at all. `vendor.tar.xz` only contains an empty `vendor/` folder.

**Comment by jacobgkau** [comment]
This is working for placing the files in their new locations, but the old files are still not removed (using the staging package built by the build server.)

**Review by jackpot51 — APPROVED** [review]

**Review by jackpot51 — APPROVED** [review]

**Comment by crawfxrd** [comment]
Replaced by #327.

**Pull request closed without merging**
