### PR TITLE
Implement additional power-saving features

### PR DESCRIPTION
**Pull request by mmstick**
## Logging

Logging is now configurable. If the `-v` / `--verbose` flag is supplied, __DEBUG__ and higher will be logged. If the `-q` / `--quiet` flag is supplied, logging will be disabled. By default, logging will be set to log __INFO__ and higher.

## Power Saving Features

__These features are hidden behind the `system76-power daemon --experimental` flag__

> Use the `-v` flag to get DEBUG messages describing the parameters being set

- SCSI/SATA hosts may now have their power policy controlled
  - __med_power_with_dipm__ will be attempted first on all levels
    - The battery profile will then attempt __min_power__
    - The balanced profile will attempt __medium_power__
    - The performance profile will attempt __max_performance__
- Power management for magnetic disks:
  - Controlling APM levels
    - **Performance** and **Balanced** set this to `254`
    - **Battery** sets this to `128`
  - Autosuspend delay
    - **Performance** and **Balanced set this to `-1` (default)
    - **Battery** sets this to `15000` milliseconds
- Power management for sound devices (`hda_intel`, `ac97`)
  - Modifies kernel module configuration files to toggle the power controller
  - Additionally sets the power save timeout value
- Radeon power profile management
  - Three configurable power parameters are the `power_profile`, `dpm_state`, and `dpm_performance_level`
  - __Performance__ sets these to `high`, `performance`, `auto`
  - __Balanced__ sets these to `auto`, `performance`, `auto`
  - __Battery__ sets these to `low`, `battery`, `low`
- iwlwifi module reloading (toggling power saving requires reloading the module: __disabled by default__)
- disable NMI Watchdog by default
- set dirty pages (controls how often pages are saved to disk)
  - **Performance** and **Balanced** set this to 15 seconds
  - **Battery** sets this to 60 seconds
- Laptop Mode Kernel Parameter
  - **Performance** and **Balanced** sets this to `0`
  - **Battery** sets this to `2`

### CODE REVIEW

**Comment by mmstick** [comment]
@brs17 If needed, we can disable all the options it's currently applying and enable them one by one.

**Comment by brs17** [comment]
After discussing this between @mmstick and @djordan2, I think we want to create an "experimental" flag for these features. Once these changes are tested on all of the current System76 product line, we will whitelist these models. Then we can get others in the Pop!_OS community to test these changes by enabling the "experimental" flag.

**Comment by ebobby** [comment]
Wouldn't these override other deamons like `tlp` ? Is the point of this utility to super seed the generic tools we have in Linux to handle power savings?

**Comment by mmstick** [comment]
@ebobby Effectively, yes. These features (in addition to the other PRs) are effectively a clean rewrite of power-saving options that `tlp` sets. You would no longer need to use tlp in addition to system76-power to gain maximal battery life.

**Comment by mmstick** [comment]
@brs17 The experimental flag has been added, and argument parsing has been switched to using Clap.

**Comment by mmstick** [comment]
Logging is now configurable. If the `-v` / `--verbose` flag is supplied, __DEBUG__ and higher will be logged. If the `-q` / `--quiet` flag is supplied, logging will be disabled. By default, logging will be set log __INFO__ and higher.

**Comment by brs17** [comment]
Couple things I noticed about this pr (mostly logging related):
1. The help title lists `system76-power 0.1.2 (UNKNOWN)` What is UNKNOWN here?
2. BUG: `system76-power profile help` currently sets the profile to performance
3. `system76-power graphics` returns `nvidia` or `intel`. `system76-power graphics power` shows `on/off` Are both of these necessary? Nowhere in the help that I saw did it tell me running `system76-power graphics` would give me the output I got.
3a. Part of me misses the older help because I didn't have to dive into multilayered help

```
fn usage() {
    eprintln!("system76-power [sub-command] [args...]");
    eprintln!("  daemon - run in daemon mode");
    eprintln!("  profile - query current profile");
    eprintln!("  profile performance - set profile to performance");
    eprintln!("  profile balanced - set profile to balanced");
    eprintln!("  profile battery - set profile to battery");
    eprintln!("  graphics - query graphics mode");
    eprintln!("  graphics intel - set graphics mode to intel");
    eprintln!("  graphics nvidia - set graphics mode to nvidia");
    eprintln!("  graphics power - query discrete graphics power state");
    eprintln!("  graphics power auto - turn off discrete graphics if not in use");
    eprintln!("  graphics power off - power off discrete graphics");
    eprintln!("  graphics power on - power on discrete graphics");

```

**Comment by brs17** [comment]
Ah, regarding that last comment, I think I just didn't read the help well enough where it says "query or set" :disappointed:

**Pull request merged**
