### PR TITLE
Add "compute" graphics mode

### PR DESCRIPTION
**Pull request by crawfxrd**
Introduce a new "compute" mode that performs all rendering on the integrated graphics, but makes the dGPU available on the bus (with the NVIDIA drivers loaded) as a compute node.

Replaces: #54
Ref: #156

### CODE REVIEW

**Comment by crawfxrd** [comment]
Would it be better to just add a `--compute` argument to `integrated` mode?

**Comment by jackpot51** [comment]
@crawfxrd I like having it be a separate mode

**Comment by jacobgkau** [comment]
With system76-power 1.1.5\~1591814391\~20.04\~baa0eed, I can switch to compute mode using the CLI, but compute mode is not listed in the top-right GNOME drop-down, and when compute mode is active, the dropdown doesn't show a dot next to any of the options. Are there plans to update gnome-shell-extension-system76-power to add compute mode to the graphical list, or is this the intended experience?

**Comment by crawfxrd** [comment]
Just pushed the extension changes: pop-os/gnome-shell-extension-system76-power#45

**Comment by crawfxrd** [comment]
I would have to defer to upstream GNOME devs on how to handle that. We already patch GNOME to not show the launch item in NVIDIA-only mode. Having it not show in compute mode would require inspecting the current Xorg configuration to see if `AllowNVIDIAGPUScreens` is set.

> Not sure if this one's an issue with Blender or compute mode.

It's compute mode; it looks like I will have to explicitly load the NVIDIA modules in the daemon so apps can use it.

**Comment by crawfxrd** [comment]
I've fixed the issue with turning the GPU on/off in compute mode  by overriding `modeset` to off.

Still need to figure out why gpu-manager unloads the drivers after us (even with `Wants=gpu-manager.service`). Otherwise, user has to modprobe after logging in.

**Pull request merged**
