### PR TITLE
1.1.12 - Use hybrid graphics by default for galp5

### PR DESCRIPTION
**Pull request by jackpot51**
This requires https://github.com/pop-os/nvidia-graphics-drivers/pull/85 and https://github.com/pop-os/system76-driver/pull/189

### CODE REVIEW

**Review by crawfxrd — APPROVED** [review]

**Comment by jacobgkau** [comment]
GNOME Initial Setup still tells me my Galago Pro defaults to Integrated mode after this change:

Screenshot from 2021-01-25 16-40-42

I think the galp5-specific message in https://github.com/pop-os/gnome-initial-setup/pull/67 needs to be undone as well.

**Comment by crawfxrd** [comment]
Or fixing and merging pop-os/gnome-initial-setup#68. I'll look into it tomorrow.

**Comment by jackpot51** [comment]
Rebased to include #213

**Comment by jackpot51** [comment]
Rebased again to include #212

**Review by jacobgkau — APPROVED** [review]
Installs into Hybrid mode. The correct copy for Hybrid mode shows during GNOME Initial Setup. External display w/ audio and launching applications on the NVIDIA GPU both work out-of-the-box.

**Review by ids1024 — APPROVED** [review]

**Pull request merged**
