### PR TITLE
Add GetProfile dbus method & PowerProfileSwitch dbus signal

### PR DESCRIPTION
**Pull request by mmstick**
Allows other applications to know which power profile is currently active. The shell extension could use this to accurately detect which profile is active, instead of default to balanced.

### CODE REVIEW

**Comment by mmstick** [comment]
Will soon be adding a signal for profile switches, so the shell extension can take advantage of it.

**Comment by isantop** [comment]
Testing this works as expected on a Darter. Approval pending results on Oryx to validate graphics switching

**Comment by isantop** [comment]
No breakage on Darter or Oryx. Graphics switching works as expected.

**Comment by mmstick** [comment]
Great. I'll merge it then.

**Pull request merged**
