### PR TITLE
Add TESTING.md

### PR DESCRIPTION
**Pull request by mmstick**
@brs17 Looking for advice on the formatting of the testing document. [Rendered](https://github.com/pop-os/system76-power/blob/6bf981395664365318fa8f9f2be4d153a6abbb18/TESTING.md)

### CODE REVIEW

**Comment by brs17** [comment]
@mmstick, would testing the daemon and the GNOME shell extension not sufficiently test the cli?

**Comment by mmstick** [comment]
@brs17 Testing either the CLI or shell extension tests the daemon.

**Comment by brs17** [comment]
@mmstick, I'm asking, if testing the gnome shell extension is sufficient to cover all functionality.

**Comment by mmstick** [comment]
Testing the shell extension, if it works, then you have verified that the daemon and shell extension work, but not the CLI frontend.

**Comment by brs17** [comment]
I'd say then, let's move the checkboxes under `Daemon` to underneath the `GNOME Shell` header. I think that helps clarify what steps should be taken to test. Is it intended to have `GNOME Shell` be a higher header than `Daemon` and `CLI`?

I do very much like the work you've put in on this @mmstick :heart_eyes: !

**Comment by mmstick** [comment]
That it is not. I will update it.

**Pull request merged**
