### PR TITLE
2018 Idioms

### PR DESCRIPTION
**Pull request by danieleades**
this is stacked on #229

### CODE REVIEW

**Comment by danieleades** [comment]
not sure if this is of interest?

**Review by bflanagin — APPROVED** [review]
We'll need to wait on the engineering team, but all works as expected...as expected :)

**Comment by danieleades** [comment]
> We'll need to wait on the engineering team, but all works as expected...as expected :)

Out of interest, do you mind talking me through the approval process?

Just curious

**Comment by jacobgkau** [comment]
> Out of interest, do you mind talking me through the approval process?
> 
> Just curious

At least two approvals are typically required to merge Pop!_OS PRs, one from the engineering team and one from the quality assurance team.

There is a [TESTING.md document](https://github.com/pop-os/system76-power/blob/master/TESTING.md) in this repository, which covers functionality we explicitly check (in addition to other case-by-case testing, depending on what the PR is doing.) If everything works as expected and no regressions are found, that's typically grounds for a QA approval.

The engineering team would probably review based on whether the code changes fit with the project and its intended direction.

**Comment by danieleades** [comment]
Also, I notice you didn't do squash merges on those last couple of pull requests- would you prefer me to rebase them? Just trying to keep your commit history tidy!

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
